  
---
- name: set up my mac
  hosts: localhost
  connection: local

  tasks:
    - name: Copy Bundle file
      shell: cp ./brew/.Brewfile ~/.Brewfile
      
    - name: Install bundle
      shell: brew bundle --global

    - name: Make config
      file:
        path: ~/.config
        state: directory
        mode: 0700
        owner: ys

    - name: Touch starship config
      file:
        path: ~/.config/starship.toml
        state: touch
      